add_newline = false

[line_break]
disabled = true

[git_status]
disabled = true

[username]
show_always = true
format = '[$user]($style) @'

[hostname]
disabled = false
ssh_only = false

[package]
disabled =true
